name: Docker build and publish
on:
    workflow_dispatch
jobs:
    CI:
        strategy:
            matrix: 
                environment: [dev, test]
                include:
                    - environment: dev
                      keyvault: mykeyvault290171
                      acr_username_secret: acr-username
                      acr_password_secret: acr-password
                      acr_name: myregistry29017
                      image_name: node-image-dev
                    - environment: test
                      keyvault: mykeyvault290181
                      acr_username_secret: acr-username
                      acr_password_secret: acr-password
                      acr_name: myregistry29018
                      image_name: node-image-test

        permissions:
            contents: 'read'
            id-token: 'write'
        

        uses: killerdaemon01/gh-templates/.github/workflows/docker-build.yml@main
        with: 
            keyvault: ${{matrix.keyvault}}
            acr_username_secret: ${{matrix.acr_username_secret}}
            acr_password_secret: ${{matrix.acr_password_secret}}
            acr_name: ${{matrix.acr_name}}
            image_name: ${{matrix.image_name}}
            environment: ${{matrix.environment}}
        secrets: inherit

    # Test:
    #     needs: Dev
    #     permissions:
    #         contents: 'read'
    #         id-token: 'write'
    #     uses: killerdaemon01/gh-templates/.github/workflows/docker-build.yml@main
    #     with: 
        #     keyvault: mykeyvault29018
        #     acr_username_secret: acr-username
        #     acr_password_secret: acr-password
        #     acr_name: myregistry29018
        #     image_name: node-image
        # secrets: inherit


    # example_matrix:
    #     strategy:
    #       matrix:
    #         environment: [dev, test]
    #         include:
    #             - environment: dev
                  
    #     runs-on: ubuntu-latest
    #     steps:
    #       - uses: actions/setup-node@v3
    #         with:
    #           node-version: ${{ matrix.version }}