name: Docker build and publish
on:
    workflow_dispatch:
jobs:
    CI:
        strategy:
            matrix: 
                environment: [dev, test]
                include:
                    - environment: dev
                      keyvault: mykeyvault290171
                      acr_username_secret: acrusername
                      acr_password_secret: acrpassword
                      acr_name: myregistry29017
                      image_name: node-image-dev
                    - environment: test
                      keyvault: mykeyvault290181
                      acr_username_secret: acrusername
                      acr_password_secret: acrpassword
                      acr_name: myregistry29018
                      image_name: node-image-test

        permissions:
            contents: 'read'
            id-token: 'write'
        

        uses: killerdaemon01/gh-templates/.github/workflows/docker-build.yml@main
        with: 
            keyvault: ${{matrix.keyvault}}
            acr_username_secret: ${{matrix.acr_username_secret}}
            acr_password_secret: ${{matrix.acr_password_secret}}
            acr_name: ${{matrix.acr_name}}
            image_name: ${{matrix.image_name}}
            environment: ${{matrix.environment}}
            tag: ${{github.sha}}
        secrets: inherit

    
  
    CD:
        permissions:
            contents: 'read'
            id-token: 'write'
        uses: killerdaemon01/gh-templates/.github/workflows/docker-deploy.yml@main
        with:
            acr_name: myregistry29017
            image_name: node-image-dev
            web_app_name: mywebapp29017
            tag: ${{github.sha}}
        secrets: inherit
