name: Docker build and publish
on:
    workflow_dispatch
jobs:
    Dev:
        permissions:
            contents: 'read'
            id-token: 'write'
        uses: killerdaemon01/gh-templates/.github/workflows/docker-build.yml@main
        with: 
            keyvault: mykeyvault29017
            acr_username_secret: acr-username
            acr_password_secret: acr-password
            acr_name: myregistry29017
            image_name: node-image
        secrets: inherit

    Test:
        needs: Dev
        permissions:
            contents: 'read'
            id-token: 'write'
        uses: killerdaemon01/gh-templates/.github/workflows/docker-build.yml@main
        with: 
            keyvault: mykeyvault29018
            acr_username_secret: acr-username
            acr_password_secret: acr-password
            acr_name: myregistry29018
            image_name: node-image
        secrets: inherit