name: Docker web app deploy
on:
    workflow_dispatch:
jobs:
    CD:
        permissions:
            contents: 'read'
            id-token: 'write'
        uses: killerdaemon01/gh-templates/.github/workflows/docker-deploy.yml@main
        with:
            acr_name: myregistry29017
            image_name: node-image-dev
            web_app_name: mywebapp29017
            slot_name: staging
        secrets: inherit